### ISSUE TITLE
Change default value of checkpoint_segments and checkpoint_completion_target for better performance? 

### ISSUE THREAD

**Issue by odunybrad** [phosphoresi/docker-postgres#1]
Thanks for providing this useful container. 

I am doing a research on configuration and have a question about two postgre config:  It seems you keep the default setting of `checkpoint_segments` to 5min and `checkpoint_completion_target` to 0.5. 

However, The [official document](https://wiki.postgresql.org/wiki/Tuning_Your_PostgreSQL_Server) recommends to set `checkpoint_segments` to at least `10`, which improves the performance:  "Unless you're running on a very small configuration, you'll almost certainly be better setting this to at least 10, which also allows usefully increasing the completion target."

The document also recommends to set `checkpoint_completion_target` to `0.9`, which is the more useful value and improves the performance: "You can spread those writes out further, lowering the average write overhead, by increasing the checkpoint_completion_target parameter to its useful maximum of 0.9"

Shall we change the default of `checkpoint_segments` to 10 and `checkpoint_completion_target` to 0.9 for better performance? 
Thanks.

**Comment by Guilhem30** [comment]
We are actually doing some tuning to postgres configuration but there are not included in the docker image yet. You should indeed change the default of checkpoint_segments and checkpoint_completion_target. You probably want to tune your postgres to ajust it to your server and workload, using this tool : https://pgtune.leopard.in.ua/
We are in the process of migrating to kubernetes, this will probably be integrated into our image at a later point.

**Comment by Guilhem30** [comment]
As we are migrating to bitnami/postgresql, this image will not be updated to add postgres configuration. 
Closing the issue
